const clues = {
  // English
  en: [
    ["Cold", "Hot"],
    ["Bad Company", "Good Company"],
    ["Terrible Movie", "Great Movie"],
    ["Ugly", "Beautiful"],
    ["Quiet Place", "Loud Place"],
    ["Villain", "Hero"],
    ["Sad", "Happy"],
    ["Cheap", "Expensive"],
    ["Easy", "Difficult"],
    ["Boring", "Exciting"],
    ["Slow", "Fast"],
    ["Empty", "Full"],
    ["Light", "Heavy"],
    ["Simple", "Complex"],
    ["Weak", "Strong"],
    ["Poor", "Rich"],
    ["Small", "Large"],
    ["Short", "Tall"],
    ["Thin", "Thick"],
    ["Narrow", "Wide"],
    ["Shallow", "Deep"],
    ["Soft", "Hard"],
    ["Smooth", "Rough"],
    ["Dry", "Wet"],
    ["Clean", "Dirty"],
    ["Young", "Old"],
    ["Fresh", "Stale"],
    ["Early", "Late"],
    ["Beginning", "End"],
    ["First", "Last"],
    ["Low", "High"],
    ["Bottom", "Top"],
    ["Down", "Up"],
    ["Far", "Near"],
    ["Outside", "Inside"],
    ["Outer", "Inner"],
    ["Front", "Back"],
    ["Past", "Future"],
    ["Ancient", "Modern"],
    ["Traditional", "Contemporary"],
    ["Conservative", "Liberal"],
    ["Unpopular", "Popular"],
    ["Unknown", "Famous"],
    ["Amateur", "Professional"],
    ["Novice", "Expert"],
    ["Failure", "Success"],
    ["Wrong", "Right"],
    ["Illegal", "Legal"],
    ["Guilty", "Innocent"],
    ["Unethical", "Ethical"],
    ["Evil", "Good"],
    ["Hate", "Love"],
    ["Enemy", "Friend"],
    ["War", "Peace"],
    ["Chaos", "Order"],
    ["Danger", "Safety"],
    ["Sick", "Healthy"],
    ["Poison", "Antidote"],
    ["Pain", "Pleasure"],
    ["Tragedy", "Comedy"],
    ["Cry", "Laugh"],
    ["Pessimist", "Optimist"],
    ["Underrated", "Overrated"],
    ["Underpaid", "Overpaid"],
    ["Undercooked", "Overcooked"],
    ["Loose", "Tight"],
    ["Flexible", "Rigid"],
    ["Casual", "Formal"],
    ["Private", "Public"],
    ["Local", "Global"],
    ["Rural", "Urban"],
    ["Fake", "Real"],
    ["Fantasy", "Reality"],
    ["Fiction", "Non-fiction"],
    ["Closed", "Open"],
    ["Introvert", "Extrovert"],
    ["Asleep", "Awake"],
    ["Night", "Day"],
    ["Winter", "Summer"],
    ["Fall", "Spring"],
    ["Plain", "Fancy"],
    ["Ordinary", "Extraordinary"],
    ["Average", "Exceptional"],
    ["Common", "Rare"],
    ["Typical", "Unique"],
    ["Normal", "Strange"],
    ["Mainstream", "Alternative"],
    ["Conformist", "Rebel"],
    ["Follower", "Leader"],
    ["Passive", "Active"],
    ["Coward", "Brave"],
    ["Calm", "Anxious"],
    ["Relaxed", "Stressed"],
    ["Sane", "Insane"],
    ["Sober", "Drunk"],
    ["Forgettable", "Memorable"],
    ["Temporary", "Permanent"],
    ["Incomplete", "Complete"],
    ["Partial", "Whole"],
    ["Individual", "Group"],
    ["Shallow", "Deep"]
  ],

  // Turkish
  tr: [
    ["Soğuk", "Sıcak"],
    ["Kötü Şirket", "İyi Şirket"],
    ["Berbat Film", "Harika Film"],
    ["Çirkin", "Güzel"],
    ["Sessiz Yer", "Gürültülü Yer"],
    ["Kötü Karakter", "Kahraman"],
    ["Üzgün", "Mutlu"],
    ["Ucuz", "Pahalı"],
    ["Kolay", "Zor"],
    ["Sıkıcı", "Heyecan Verici"],
    ["Yavaş", "Hızlı"],
    ["Boş", "Dolu"],
    ["Hafif", "Ağır"],
    ["Basit", "Karmaşık"],
    ["Zayıf", "Güçlü"],
    ["Fakir", "Zengin"],
    ["Küçük", "Büyük"],
    ["Kısa", "Uzun"],
    ["İnce", "Kalın"],
    ["Dar", "Geniş"],
    ["Sığ", "Derin"],
    ["Yumuşak", "Sert"],
    ["Pürüzsüz", "Pürüzlü"],
    ["Kuru", "Islak"],
    ["Temiz", "Kirli"],
    ["Genç", "Yaşlı"],
    ["Taze", "Bayat"],
    ["Erken", "Geç"],
    ["Başlangıç", "Son"],
    ["İlk", "Son"],
    ["Alçak", "Yüksek"],
    ["Alt", "Üst"],
    ["Aşağı", "Yukarı"],
    ["Uzak", "Yakın"],
    ["Dışarı", "İçeri"],
    ["Dış", "İç"],
    ["Ön", "Arka"],
    ["Geçmiş", "Gelecek"],
    ["Antik", "Modern"],
    ["Geleneksel", "Çağdaş"],
    ["Muhafazakar", "Liberal"],
    ["Popüler Olmayan", "Popüler"],
    ["Bilinmeyen", "Ünlü"],
    ["Amatör", "Profesyonel"],
    ["Acemi", "Uzman"],
    ["Başarısızlık", "Başarı"],
    ["Yanlış", "Doğru"],
    ["Yasadışı", "Yasal"],
    ["Suçlu", "Masum"],
    ["Etik Dışı", "Etik"],
    ["Kötü", "İyi"],
    ["Nefret", "Aşk"],
    ["Düşman", "Arkadaş"],
    ["Savaş", "Barış"],
    ["Kaos", "Düzen"],
    ["Tehlike", "Güvenlik"],
    ["Hasta", "Sağlıklı"],
    ["Poison", "Antidote"],
    ["Acı", "Zevk"],
    ["Trajedi", "Komedi"],
    ["Ağlamak", "Gülmek"],
    ["Karamsar", "İyimser"],
    ["Az Değer Verilen", "Abartılan"],
    ["Az Ödenen", "Fazla Ödenen"],
    ["Az Pişmiş", "Fazla Pişmiş"],
    ["Gevşek", "Sıkı"],
    ["Esnek", "Katı"],
    ["Gündelik", "Resmi"],
    ["Özel", "Kamusal"],
    ["Yerel", "Küresel"],
    ["Kırsal", "Kentsel"],
    ["Sahte", "Gerçek"],
    ["Fantasy", "Reality"],
    ["Fiction", "Non-fiction"],
    ["Kapalı", "Açık"],
    ["İçe Dönük", "Dışa Dönük"],
    ["Uykuda", "Uyanık"],
    ["Gece", "Gündüz"],
    ["Kış", "Yaz"],
    ["Sonbahar", "İlkbahar"],
    ["Sade", "Süslü"],
    ["Sıradan", "Olağanüstü"],
    ["Ortalama", "İstisnai"],
    ["Yaygın", "Nadir"],
    ["Tipik", "Benzersiz"],
    ["Normal", "Tuhaf"],
    ["Mainstream", "Alternative"],
    ["Conformist", "Rebel"],
    ["Takipçi", "Lider"],
    ["Pasif", "Aktif"],
    ["Korkak", "Cesur"],
    ["Sakin", "Endişeli"],
    ["Rahat", "Stresli"],
    ["Akıllı", "Deli"],
    ["Ayık", "Sarhoş"],
    ["Unutulabilir", "Unutulmaz"],
    ["Geçici", "Kalıcı"],
    ["Eksik", "Tam"],
    ["Kısmi", "Bütün"],
    ["Birey", "Grup"],
    ["Yüzeysel", "Derin"]
  ],

  // Spanish
  es: [
    ["Frío", "Caliente"],
    ["Mala Compañía", "Buena Compañía"],
    ["Película Terrible", "Película Excelente"],
    ["Feo", "Hermoso"],
    ["Lugar Tranquilo", "Lugar Ruidoso"],
    ["Villano", "Héroe"],
    ["Triste", "Feliz"],
    ["Barato", "Caro"],
    ["Fácil", "Difícil"],
    ["Aburrido", "Emocionante"],
    ["Lento", "Rápido"],
    ["Vacío", "Lleno"],
    ["Ligero", "Pesado"],
    ["Simple", "Complejo"],
    ["Débil", "Fuerte"],
    ["Pobre", "Rico"],
    ["Pequeño", "Grande"],
    ["Bajo", "Alto"],
    ["Delgado", "Grueso"],
    ["Estrecho", "Ancho"],
    ["Superficial", "Profundo"],
    ["Suave", "Duro"],
    ["Liso", "Rugoso"],
    ["Seco", "Mojado"],
    ["Limpio", "Sucio"],
    ["Joven", "Viejo"],
    ["Fresco", "Rancio"],
    ["Temprano", "Tarde"],
    ["Principio", "Fin"],
    ["Primero", "Último"],
    ["Bajo", "Alto"],
    ["Abajo", "Arriba"],
    ["Lejos", "Cerca"],
    ["Exterior", "Interior"],
    ["Externo", "Interno"],
    ["Frente", "Atrás"],
    ["Pasado", "Futuro"],
    ["Antiguo", "Moderno"],
    ["Tradicional", "Contemporáneo"],
    ["Conservador", "Liberal"],
    ["Impopular", "Popular"],
    ["Desconocido", "Famoso"],
    ["Amateur", "Profesional"],
    ["Novato", "Experto"],
    ["Fracaso", "Éxito"],
    ["Incorrecto", "Correcto"],
    ["Ilegal", "Legal"],
    ["Culpable", "Inocente"],
    ["No Ético", "Ético"],
    ["Mal", "Bien"],
    ["Odio", "Amor"],
    ["Enemigo", "Amigo"],
    ["Guerra", "Paz"],
    ["Caos", "Orden"],
    ["Peligro", "Seguridad"],
    ["Enfermo", "Saludable"],
    ["Veneno", "Antídoto"],
    ["Dolor", "Placer"],
    ["Tragedia", "Comedia"],
    ["Llorar", "Reír"],
    ["Pesimista", "Optimista"],
    ["Infravalorado", "Sobrevalorado"],
    ["Mal Pagado", "Bien Pagado"],
    ["Poco Cocinado", "Muy Cocinado"],
    ["Suelto", "Apretado"],
    ["Flexible", "Rígido"],
    ["Casual", "Formal"],
    ["Privado", "Público"],
    ["Local", "Global"],
    ["Rural", "Urbano"],
    ["Falso", "Real"],
    ["Fantasía", "Realidad"],
    ["Ficción", "No Ficción"],
    ["Cerrado", "Abierto"],
    ["Introvertido", "Extrovertido"],
    ["Dormido", "Despierto"],
    ["Noche", "Día"],
    ["Invierno", "Verano"],
    ["Otoño", "Primavera"],
    ["Sencillo", "Lujoso"],
    ["Ordinario", "Extraordinario"],
    ["Promedio", "Excepcional"],
    ["Común", "Raro"],
    ["Típico", "Único"],
    ["Normal", "Extraño"],
    ["Popular", "Alternativo"],
    ["Conformista", "Rebelde"],
    ["Seguidor", "Líder"],
    ["Pasivo", "Activo"],
    ["Cobarde", "Valiente"],
    ["Tranquilo", "Ansioso"],
    ["Relajado", "Estresado"],
    ["São", "Louco"],
    ["Sóbrio", "Bêbado"],
    ["Esquecível", "Memorável"],
    ["Temporal", "Permanente"],
    ["Incompleto", "Completo"],
    ["Parcial", "Total"],
    ["Individual", "Grupo"],
    ["Superficial", "Profundo"]
  ],
  
  // Mandarin Chinese
  zh: [
    ["冷", "热"],
    ["坏公司", "好公司"],
    ["糟糕的电影", "好电影"],
    ["丑陋", "美丽"],
    ["安静的地方", "嘈杂的地方"],
    ["反派", "英雄"],
    ["悲伤", "快乐"],
    ["便宜", "昂贵"],
    ["容易", "困难"],
    ["无聊", "刺激"],
    ["慢", "快"],
    ["空", "满"],
    ["轻", "重"],
    ["简单", "复杂"],
    ["弱", "强"],
    ["贫穷", "富有"],
    ["小", "大"],
    ["矮", "高"],
    ["薄", "厚"],
    ["窄", "宽"],
    ["浅", "深"],
    ["软", "硬"],
    ["光滑", "粗糙"],
    ["干", "湿"],
    ["干净", "脏"],
    ["年轻", "年老"],
    ["新鲜", "陈旧"],
    ["早", "晚"],
    ["开始", "结束"],
    ["第一", "最后"],
    ["低", "高"],
    ["底部", "顶部"],
    ["下", "上"],
    ["远", "近"],
    ["外面", "里面"],
    ["外部", "内部"],
    ["前面", "后面"],
    ["过去", "未来"],
    ["古代", "现代"],
    ["传统", "当代"],
    ["保守", "自由"],
    ["不受欢迎", "流行"],
    ["无名", "有名"],
    ["业余", "专业"],
    ["新手", "专家"],
    ["失败", "成功"],
    ["错", "对"],
    ["非法", "合法"],
    ["有罪", "无辜"],
    ["不道德", "道德"],
    ["邪恶", "善良"],
    ["恨", "爱"],
    ["敌人", "朋友"],
    ["战争", "和平"],
    ["混乱", "秩序"],
    ["危险", "安全"],
    ["生病", "健康"],
    ["毒药", "解药"],
    ["痛苦", "愉悦"],
    ["悲剧", "喜剧"],
    ["哭", "笑"],
    ["悲观主义者", "乐观主义者"],
    ["被低估", "被高估"],
    ["报酬低", "报酬高"],
    ["烹饪不足", "烹饪过度"],
    ["松", "紧"],
    ["灵活", "僵硬"],
    ["休闲", "正式"],
    ["私人", "公共"],
    ["本地", "全球"],
    ["农村", "城市"],
    ["假", "真"],
    ["幻想", "现实"],
    ["虚构", "非虚构"],
    ["关闭", "开放"],
    ["内向", "外向"],
    ["睡着", "醒着"],
    ["夜晚", "白天"],
    ["冬天", "夏天"],
    ["秋天", "春天"],
    ["朴素", "华丽"],
    ["普通", "非凡"],
    ["平均", "杰出"],
    ["常见", "稀有"],
    ["典型", "独特"],
    ["正常", "奇怪"],
    ["主流", "另类"],
    ["从众", "叛逆"],
    ["追随者", "领导者"],
    ["被动", "主动"],
    ["懦夫", "勇敢"],
    ["平静", "焦虑"],
    ["放松", "紧张"],
    ["理智", "疯狂"],
    ["清醒", "醉酒"],
    ["可忘", "难忘"],
    ["暂时", "永久"],
    ["不完整", "完整"],
    ["部分", "整体"],
    ["个人", "团体"],
    ["肤浅", "深刻"]
  ],
  
  // Hindi
  hi: [
    ["ठंडा", "गर्म"],
    ["बुरी कंपनी", "अच्छी कंपनी"],
    ["बुरी फिल्म", "अच्छी फिल्म"],
    ["बदसूरत", "सुंदर"],
    ["शांत जगह", "शोरगुल वाली जगह"],
    ["खलनायक", "नायक"],
    ["दुःखी", "सुखी"],
    ["सस्ता", "महंगा"],
    ["आसान", "मुश्किल"],
    ["उबाऊ", "रोमांचक"],
    ["धीमा", "तेज़"],
    ["खाली", "भरा हुआ"],
    ["हल्का", "भारी"],
    ["सरल", "जटिल"],
    ["कमज़ोर", "मज़बूत"],
    ["गरीब", "धंधी"],
    ["छोटा", "बड़ा"],
    ["काटो", "लंबा"],
    ["पतला", "मोटा"],
    ["संकीर्ण", "प्रशस्त"],
    ["अगभीर", "गभीर"],
    ["नरम", "शक्त"],
    ["मसृण", "खसखसे"],
    ["शुकनो", "भेजा"],
    ["परिष्कार", "नोंरा"],
    ["तरुण", "बृद्ध"],
    ["ताजा", "बासी"],
    ["आगे", "परे"],
    ["शुरु", "शेष"],
    ["प्रथम", "शेष"],
    ["निचु", "उंचु"],
    ["नीचे", "उपरे"],
    ["दूर", "काछे"],
    ["बायरे", "भितरे"],
    ["बाह्य", "अभ्यन्तरीण"],
    ["सामने", "पिछने"],
    ["अतीत", "भविष्य"],
    ["प्राचीन", "आधुनिक"],
    ["अतिहायीगत", "समसाम्यक"],
    ["रक्षणशील", "उदारनायतिक"],
    ["अजनप्रिय", "जनप्रिय"],
    ["अज्ञात", "बिख्यात"],
    ["अपेशादार", "पेशादार"],
    ["नबीन", "बिशेषज्ञ"],
    ["ब्यर्थता", "साफल्य"],
    ["भुल", "सठिक"],
    ["बेआइनी", "आइनी"],
    ["अपराधी", "निरपराध"],
    ["अनैतिक", "नैतिक"],
    ["खाराप", "भालो"],
    ["घृणा", "भालोबासा"],
    ["शत्रु", "बन्धु"],
    ["युद्ध", "शान्ति"],
    ["बिशृङ्खला", "शृङ्खला"],
    ["बिपद", "निरापत्ता"],
    ["असुस्थ", "सुस्थ"],
    ["बिष", "प्रतिषेधक"],
    ["ब्यथा", "आनन्द"],
    ["ट्र्याजेडी", "कमेडी"],
    ["कान्ना", "हसी"],
    ["निराशाबादी", "आशाबादी"],
    ["अमूल्यायित", "अतिमूल्यायित"],
    ["कम वेतन", "बैशि वेतन"],
    ["कम रान्ना", "बैशि रान्ना"],
    ["आलगा", "आंटसांट"],
    ["नमनीय", "कठोर"],
    ["अनानुष्ठानिक", "आनुष्ठानिक"],
    ["ब्यक्तिगत", "सार्बजनीय"],
    ["स्थानीय", "बिश्वव्यापी"],
    ["ग्रामीण", "शहुरे"],
    ["नकल", "आसल"],
    ["कल्पना", "बास्तवता"],
    ["कल्पकाहिनी", "अकल्पकाहिनी"],
    ["बन्ध", "खोला"],
    ["अन्तर्मुखी", "बहिर्मुखी"],
    ["घुमन्त", "जाग्रत"],
    ["रात", "दिन"],
    ["शीत", "ग्रीष्म"],
    ["शरॎ", "बसन्त"],
    ["साधारण", "असाधारण"],
    ["गड़", "असाधारण"],
    ["साधारण", "बिरल"],
    ["साधारण", "अनन्य"],
    ["स्वाभाबिक", "अद्भुत"],
    ["मूलधारा", "बिकल्प"],
    ["अनुगत", "बिद्रोही"],
    ["अनुसारी", "नेता"],
    ["निष्क्रिय", "सक्रिय"],
    ["कापुरुष", "साहसी"],
    ["शान्त", "उद्बिग्न"],
    ["आरामदायक", "मानसिक चापयुक्त"],
    ["सुस्थ मस्तिष्क", "पागल"],
    ["सोबार", "माताल"],
    ["भुले जाओयो", "स्मरणीय"],
    ["अस्थायी", "स्थायी"],
    ["असम्पूर्ण", "सम्पूर्ण"],
    ["आंशिक", "सम्पूर्ण"],
    ["ब्यक्ति", "दल"],
    ["साधारण", "गभीर"]
  ],
  
  // Portuguese
  pt: [
    ["Frio", "Quente"],
    ["Má Companhia", "Boa Companhia"],
    ["Filme Terrível", "Ótimo Filme"],
    ["Feio", "Bonito"],
    ["Lugar Silencioso", "Lugar Barulhento"],
    ["Vilão", "Herói"],
    ["Triste", "Feliz"],
    ["Barato", "Caro"],
    ["Fácil", "Difícil"],
    ["Chato", "Emocionante"],
    ["Lento", "Rápido"],
    ["Vazio", "Cheio"],
    ["Leve", "Pesado"],
    ["Simples", "Complexo"],
    ["Fraco", "Forte"],
    ["Pobre", "Rico"],
    ["Pequeno", "Grande"],
    ["Baixo", "Alto"],
    ["Fino", "Grosso"],
    ["Estreito", "Largo"],
    ["Raso", "Profundo"],
    ["Macio", "Duro"],
    ["Liso", "Áspero"],
    ["Seco", "Molhado"],
    ["Limpo", "Sujo"],
    ["Jovem", "Velho"],
    ["Fresco", "Estragado"],
    ["Cedo", "Tarde"],
    ["Começo", "Fim"],
    ["Primeiro", "Último"],
    ["Baixo", "Alto"],
    ["Fundo", "Topo"],
    ["Para Baixo", "Para Cima"],
    ["Longe", "Perto"],
    ["Fora", "Dentro"],
    ["Exterior", "Interior"],
    ["Frente", "Trás"],
    ["Passado", "Futuro"],
    ["Antigo", "Moderno"],
    ["Tradicional", "Contemporâneo"],
    ["Conservador", "Liberal"],
    ["Impopular", "Popular"],
    ["Desconhecido", "Famoso"],
    ["Amador", "Profissional"],
    ["Novato", "Especialista"],
    ["Fracasso", "Sucesso"],
    ["Errado", "Certo"],
    ["Ilegal", "Legal"],
    ["Culpado", "Inocente"],
    ["Antiético", "Ético"],
    ["Mal", "Bem"],
    ["Ódio", "Amor"],
    ["Inimigo", "Amigo"],
    ["Guerra", "Paz"],
    ["Caos", "Ordem"],
    ["Perigo", "Segurança"],
    ["Doente", "Saudável"],
    ["Veneno", "Antídoto"],
    ["Dor", "Prazer"],
    ["Tragédia", "Comédia"],
    ["Chorar", "Rir"],
    ["Pessimista", "Otimista"],
    ["Subvalorizado", "Supervalorizado"],
    ["Mal Pago", "Bem Pago"],
    ["Mal Cozido", "Bem Cozido"],
    ["Solto", "Apertado"],
    ["Flexível", "Rígido"],
    ["Casual", "Formal"],
    ["Privado", "Público"],
    ["Local", "Global"],
    ["Rural", "Urbano"],
    ["Falso", "Real"],
    ["Fantasia", "Realidade"],
    ["Ficção", "Não-Ficção"],
    ["Fechado", "Aberto"],
    ["Introvertido", "Extrovertido"],
    ["Dormindo", "Acordado"],
    ["Noite", "Dia"],
    ["Inverno", "Verão"],
    ["Outono", "Primavera"],
    ["Simples", "Luxuoso"],
    ["Comum", "Extraordinário"],
    ["Médio", "Excepcional"],
    ["Comum", "Raro"],
    ["Típico", "Único"],
    ["Normal", "Estranho"],
    ["Mainstream", "Alternativo"],
    ["Conformista", "Rebelde"],
    ["Seguidor", "Líder"],
    ["Passivo", "Ativo"],
    ["Covarde", "Corajoso"],
    ["Calmo", "Ansioso"],
    ["Relaxado", "Estressado"],
    ["São", "Louco"],
    ["Sóbrio", "Bêbado"],
    ["Esquecível", "Memorável"],
    ["Temporário", "Permanente"],
    ["Incompleto", "Completo"],
    ["Parcial", "Total"],
    ["Individual", "Grupo"],
    ["Superficial", "Profundo"]
  ],
  
  // Bengali
  bn: [
    ["ঠান্ডা", "গরম"],
    ["খারাপ সঙ্গী", "ভালো সঙ্গী"],
    ["খারাপ সিনেমা", "ভালো সিনেমা"],
    ["কুৎসিত", "সুন্দর"],
    ["নিরব স্থান", "শব্দময় স্থান"],
    ["খলনায়ক", "নায়ক"],
    ["দুঃখী", "সুখী"],
    ["সস্তা", "দামী"],
    ["সহজ", "কঠিন"],
    ["বিরক্তিকর", "উত্তেজনাপূর্ণ"],
    ["ধীর", "দ্রুত"],
    ["খালি", "পূর্ণ"],
    ["হালকা", "ভারী"],
    ["সরল", "জটিল"],
    ["দুর্বল", "শক্তিশালী"],
    ["গরিব", "ধনী"],
    ["ছোট", "বড়"],
    ["খাটো", "লম্বা"],
    ["পাতলা", "মোটা"],
    ["সংকীর্ণ", "প্রশস্ত"],
    ["অগভীর", "গভীর"],
    ["নরম", "শক্ত"],
    ["মসৃণ", "খসখসে"],
    ["শুকনো", "ভেজা"],
    ["পরিষ্কার", "নোংরা"],
    ["তরুণ", "বৃদ্ধ"],
    ["তাজা", "বাসি"],
    ["আগে", "পরে"],
    ["শুরু", "শেষ"],
    ["প্রথম", "শেষ"],
    ["নিচু", "উঁচু"],
    ["নীচে", "উপরে"],
    ["দূরে", "কাছে"],
    ["বাইরে", "ভিতরে"],
    ["বাহ্যিক", "অভ্যন্তরীণ"],
    ["সামনে", "পিছনে"],
    ["অতীত", "ভবিষ্যৎ"],
    ["প্রাচীন", "আধুনিক"],
    ["ঐতিহ্যগত", "সমসাময়িক"],
    ["রক্ষণশীল", "উদারনৈতিক"],
    ["অজনপ্রিয়", "জনপ্রিয়"],
    ["অজ্ঞাত", "বিখ্যাত"],
    ["অপেশাদার", "পেশাদার"],
    ["নবীন", "বিশেষজ্ঞ"],
    ["ব্যর্থতা", "সাফল্য"],
    ["ভুল", "সঠিক"],
    ["বেআইনি", "আইনি"],
    ["অপরাধী", "নিরপরাধ"],
    ["অনৈতিক", "নৈতিক"],
    ["খারাপ", "ভালো"],
    ["ঘৃণা", "ভালোবাসা"],
    ["শত্রু", "বন্ধু"],
    ["যুদ্ধ", "শান্তি"],
    ["বিশৃঙ্খলা", "শृঙ্খলা"],
    ["বিপদ", "নিরাপত্তা"],
    ["অসুস্থ", "সুস্থ"],
    ["বিষ", "প্রতিষেধক"],
    ["ব্যথা", "আনন্দ"],
    ["ট্র্যাজেডি", "কমেডি"],
    ["কান্না", "হাসি"],
    ["নিরাশাবাদী", "আশাবাদী"],
    ["অমূল্যায়িত", "অতিমূল্যায়িত"],
    ["কম বেতন", "বেশি বেতন"],
    ["কম রান্না", "বেশি রান্না"],
    ["আলগা", "আঁটসাঁট"],
    ["নমনীয়", "কঠোর"],
    ["অনানুষ্ঠানিক", "আনুষ্ঠানিক"],
    ["ব্যক্তিগত", "সার্বজনীন"],
    ["স্থানীয়", "বিশ্বব্যাপী"],
    ["গ্রামীণ", "শহুরে"],
    ["নকল", "আসল"],
    ["কল্পনা", "বাস্তবতা"],
    ["কল্পকাহিনী", "অকল্পকাহিনী"],
    ["বন্ধ", "খোলা"],
    ["অন্তর্মুখী", "বহির্মুখী"],
    ["ঘুমন্ত", "জাগ্রত"],
    ["রাত", "দিন"],
    ["শীত", "গ্রীষ্ম"],
    ["শরৎ", "বসন্ত"],
    ["সাধারণ", "অসাধারণ"],
    ["গড়", "অসাধারণ"],
    ["সাধারণ", "বিরল"],
    ["সাধারণ", "অনন্য"],
    ["স্বাভাবিক", "অদ্ভুত"],
    ["মূলধারা", "বিকল্প"],
    ["অনুগত", "বিদ্রোহী"],
    ["অনুসারী", "নেতা"],
    ["নিষ্ক্রিয়", "সক্রিয়"],
    ["কাপুরুষ", "সাহসী"],
    ["শান্ত", "উদ্বিগ্ন"],
    ["আরামদায়ক", "মানসিক চাপযুক্ত"],
    ["সুস্থ মস্তিষ্ক", "পাগল"],
    ["সোবার", "মাতাল"],
    ["ভুলে যাওয়া", "স্মরণীয়"],
    ["অস্থায়ী", "স্থায়ী"],
    ["অসম্পূর্ণ", "সম্পূর্ণ"],
    ["আংশিক", "সম্পূর্ণ"],
    ["ব্যক্তি", "দল"],
    ["সাধারণ", "গভীর"]
  ],
  
  // Russian
  ru: [
    ["Холодный", "Горячий"],
    ["Плохая компания", "Хорошая компания"],
    ["Ужасный фильм", "Отличный фильм"],
    ["Уродливый", "Красивый"],
    ["Тихое место", "Шумное место"],
    ["Злодей", "Герой"],
    ["Грустный", "Счастливый"],
    ["Дешевый", "Дорогой"],
    ["Легкий", "Трудный"],
    ["Скучный", "Захватывающий"],
    ["Медленный", "Быстрый"],
    ["Пустой", "Полный"],
    ["Легкий", "Тяжелый"],
    ["Простой", "Сложный"],
    ["Слабый", "Сильный"],
    ["Бедный", "Богатый"],
    ["Маленький", "Большой"],
    ["Низкий", "Высокий"],
    ["Тонкий", "Толстый"],
    ["Узкий", "Широкий"],
    ["Мелкий", "Глубокий"],
    ["Мягкий", "Твердый"],
    ["Гладкий", "Шероховатый"],
    ["Сухой", "Мокрый"],
    ["Чистый", "Грязный"],
    ["Молодой", "Старый"],
    ["Свежий", "Несвежий"],
    ["Ранний", "Поздний"],
    ["Начало", "Конец"],
    ["Первый", "Последний"],
    ["Низкий", "Высокий"],
    ["Низ", "Верх"],
    ["Вниз", "Вверх"],
    ["Далеко", "Близко"],
    ["Снаружи", "Внутри"],
    ["Внешний", "Внутренний"],
    ["Перед", "Зад"],
    ["Прошлое", "Будущее"],
    ["Древний", "Современный"],
    ["Традиционный", "Современный"],
    ["Консервативный", "Либеральный"],
    ["Непопулярный", "Популярный"],
    ["Неизвестный", "Знаменитый"],
    ["Любитель", "Профессионал"],
    ["Новичок", "Эксперт"],
    ["Неудача", "Успех"],
    ["Неправильный", "Правильный"],
    ["Незаконный", "Законный"],
    ["Виновный", "Невиновный"],
    ["Неэтичный", "Этичный"],
    ["Злой", "Добрый"],
    ["Ненависть", "Любовь"],
    ["Враг", "Друг"],
    ["Война", "Мир"],
    ["Хаос", "Порядок"],
    ["Опасность", "Безопасность"],
    ["Больной", "Здоровый"],
    ["Яд", "Противоядие"],
    ["Боль", "Удовольствие"],
    ["Трагедия", "Комедия"],
    ["Плач", "Смех"],
    ["Пессимист", "Оптимист"],
    ["Недооцененный", "Переоцененный"],
    ["Недоплаченный", "Переплаченный"],
    ["Недоготовленный", "Переготовленный"],
    ["Свободный", "Тугой"],
    ["Гибкий", "Жесткий"],
    ["Повседневный", "Формальный"],
    ["Частный", "Общественный"],
    ["Местный", "Глобальный"],
    ["Сельский", "Городской"],
    ["Поддельный", "Настоящий"],
    ["Фантазия", "Реальность"],
    ["Вымысел", "Документальный"],
    ["Закрытый", "Открытый"],
    ["Интроверт", "Экстраверт"],
    ["Спящий", "Бодрствующий"],
    ["Ночь", "День"],
    ["Зима", "Лето"],
    ["Осень", "Весна"],
    ["Обычный", "Необычный"],
    ["Обыкновенный", "Выдающийся"],
    ["Средний", "Исключительный"],
    ["Распространенный", "Редкий"],
    ["Типичный", "Уникальный"],
    ["Нормальный", "Странный"],
    ["Мейнстрим", "Альтернативный"],
    ["Конформист", "Бунтарь"],
    ["Последователь", "Лидер"],
    ["Пассивный", "Активный"],
    ["Трус", "Храбрый"],
    ["Спокойный", "Тревожный"],
    ["Расслабленный", "Напряженный"],
    ["Вменяемый", "Безумный"],
    ["Трезвый", "Пьяный"],
    ["Незапоминающийся", "Запоминающийся"],
    ["Временный", "Постоянный"],
    ["Неполный", "Полный"],
    ["Частичный", "Целый"],
    ["Индивидуальный", "Групповой"],
    ["Поверхностный", "Глубокий"]
  ],
  
  // Japanese
  ja: [
    ["冷たい", "熱い"],
    ["悪い会社", "良い会社"],
    ["ひどい映画", "素晴らしい映画"],
    ["醜い", "美しい"],
    ["静かな場所", "騒がしい場所"],
    ["悪役", "英雄"],
    ["悲しい", "幸せ"],
    ["安い", "高い"],
    ["簡単", "難しい"],
    ["退屈", "エキサイティング"],
    ["遅い", "速い"],
    ["空", "満杯"],
    ["軽い", "重い"],
    ["単純", "複雑"],
    ["弱い", "強い"],
    ["貧しい", "豊か"],
    ["小さい", "大きい"],
    ["低い", "高い"],
    ["薄い", "厚い"],
    ["狭い", "広い"],
    ["浅い", "深い"],
    ["柔らかい", "硬い"],
    ["滑らか", "粗い"],
    ["乾いた", "濡れた"],
    ["清潔", "汚い"],
    ["若い", "老いた"],
    ["新鮮", "古い"],
    ["早い", "遅い"],
    ["始まり", "終わり"],
    ["最初", "最後"],
    ["低い", "高い"],
    ["底", "頂上"],
    ["下", "上"],
    ["遠い", "近い"],
    ["外", "内"],
    ["外部", "内部"],
    ["前", "後ろ"],
    ["過去", "未来"],
    ["古代", "現代"],
    ["伝統的", "現代的"],
    ["保守的", "自由主義的"],
    ["不人気", "人気"],
    ["無名", "有名"],
    ["アマチュア", "プロフェッショナル"],
    ["初心者", "専門家"],
    ["失敗", "成功"],
    ["間違い", "正しい"],
    ["違法", "合法"],
    ["有罪", "無実"],
    ["非倫理的", "倫理的"],
    ["悪", "善"],
    ["憎しみ", "愛"],
    ["敵", "友達"],
    ["戦争", "平和"],
    ["混沌", "秩序"],
    ["危険", "安全"],
    ["病気", "健康"],
    ["毒", "解毒剤"],
    ["痛み", "快楽"],
    ["悲劇", "喜劇"],
    ["泣く", "笑う"],
    ["悲観主義者", "楽観主義者"],
    ["過小評価", "過大評価"],
    ["低賃金", "高賃金"],
    ["生煮え", "焼きすぎ"],
    ["緩い", "きつい"],
    ["柔軟", "固い"],
    ["カジュアル", "フォーマル"],
    ["個人的", "公共"],
    ["地元", "世界的"],
    ["田舎", "都会"],
    ["偽物", "本物"],
    ["空想", "現実"],
    ["フィクション", "ノンフィクション"],
    ["閉じた", "開いた"],
    ["内向的", "外向的"],
    ["眠っている", "起きている"],
    ["夜", "昼"],
    ["冬", "夏"],
    ["秋", "春"],
    ["質素", "豪華"],
    ["普通", "特別"],
    ["平均的", "例外的"],
    ["一般的", "稀少"],
    ["典型的", "ユニーク"],
    ["普通", "奇妙"],
    ["主流", "代替"],
    ["従順", "反抗的"],
    ["フォロワー", "リーダー"],
    ["受動的", "能動的"],
    ["臆病", "勇敢"],
    ["落ち着いた", "不安"],
    ["リラックス", "ストレス"],
    ["正気", "狂気"],
    ["酔っていない", "酔った"],
    ["忘れやすい", "記憶に残る"],
    ["一時的", "永久的"],
    ["不完全", "完全"],
    ["部分的", "全体的"],
    ["個人", "グループ"],
    ["表面的", "深い"]
  ],
  
  // Vietnamese
  vi: [
    ["Lạnh", "Nóng"],
    ["Công ty xấu", "Công ty tốt"],
    ["Phim tồi", "Phim hay"],
    ["Xấu xí", "Đẹp"],
    ["Nơi yên tĩnh", "Nơi ồn ào"],
    ["Kẻ xấu", "Anh hùng"],
    ["Buồn", "Vui"],
    ["Rẻ", "Đắt"],
    ["Dễ", "Khó"],
    ["Nhàm chán", "Thú vị"],
    ["Chậm", "Nhanh"],
    ["Trống", "Đầy"],
    ["Nhẹ", "Nặng"],
    ["Đơn giản", "Phức tạp"],
    ["Yếu", "Mạnh"],
    ["Nghèo", "Giàu"],
    ["Nhỏ", "Lớn"],
    ["Thấp", "Cao"],
    ["Mỏng", "Dày"],
    ["Hẹp", "Rộng"],
    ["Nông", "Sâu"],
    ["Mềm", "Cứng"],
    ["Trơn", "Nhám"],
    ["Khô", "Ướt"],
    ["Sạch", "Bẩn"],
    ["Trẻ", "Già"],
    ["Tươi", "Cũ"],
    ["Sớm", "Muộn"],
    ["Bắt đầu", "Kết thúc"],
    ["Đầu tiên", "Cuối cùng"],
    ["Thấp", "Cao"],
    ["Dưới", "Trên"],
    ["Xuống", "Lên"],
    ["Xa", "Gần"],
    ["Bên ngoài", "Bên trong"],
    ["Ngoại", "Nội"],
    ["Trước", "Sau"],
    ["Quá khứ", "Tương lai"],
    ["Cổ", "Hiện đại"],
    ["Truyền thống", "Đương đại"],
    ["Bảo thủ", "Tự do"],
    ["Không phổ biến", "Phổ biến"],
    ["Không nổi tiếng", "Nổi tiếng"],
    ["Nghiệp dư", "Chuyên nghiệp"],
    ["Người mới", "Chuyên gia"],
    ["Thất bại", "Thành công"],
    ["Sai", "Đúng"],
    ["Bất hợp pháp", "Hợp pháp"],
    ["Có tội", "Vô tội"],
    ["Phi đạo đức", "Đạo đức"],
    ["Ác", "Thiện"],
    ["Ghét", "Yêu"],
    ["Kẻ thù", "Bạn"],
    ["Chiến tranh", "Hòa bình"],
    ["Hỗn loạn", "Trật tự"],
    ["Nguy hiểm", "An toàn"],
    ["Bệnh", "Khỏe"],
    ["Chất độc", "Thuốc giải"],
    ["Đau", "Sướng"],
    ["Bi kịch", "Hài kịch"],
    ["Khóc", "Cười"],
    ["Bi quan", "Lạc quan"],
    ["Đánh giá thấp", "Đánh giá cao"],
    ["Trả lương thấp", "Trả lương cao"],
    ["Chưa chín", "Quá chín"],
    ["Lỏng", "Chặt"],
    ["Linh hoạt", "Cứng nhắc"],
    ["Thường phục", "Trang trọng"],
    ["Riêng tư", "Công cộng"],
    ["Địa phương", "Toàn cầu"],
    ["Nông thôn", "Thành thị"],
    ["Giả", "Thật"],
    ["Ảo tưởng", "Thực tế"],
    ["Hư cấu", "Phi hư cấu"],
    ["Đóng", "Mở"],
    ["Hướng nội", "Hướng ngoại"],
    ["Ngủ", "Thức"],
    ["Đêm", "Ngày"],
    ["Mùa đông", "Mùa hè"],
    ["Mùa thu", "Mùa xuân"],
    ["Giản dị", "Xa hoa"],
    ["Bình thường", "Phi thường"],
    ["Trung bình", "Xuất sắc"],
    ["Phổ biến", "Hiếm"],
    ["Điển hình", "Độc đáo"],
    ["Bình thường", "Kỳ lạ"],
    ["Dòng chính", "Thay thế"],
    ["Tuân thủ", "Nổi loạn"],
    ["Người theo", "Người dẫn đầu"],
    ["Thụ động", "Chủ động"],
    ["Hèn nhát", "Dũng cảm"],
    ["Bình tĩnh", "Lo lắng"],
    ["Thư giãn", "Căng thẳng"],
    ["Tỉnh táo", "Điên rồ"],
    ["Tỉnh", "Say"],
    ["Dễ quên", "Đáng nhớ"],
    ["Tạm thời", "Vĩnh viễn"],
    ["Không đầy đủ", "Hoàn chỉnh"],
    ["Một phần", "Toàn bộ"],
    ["Cá nhân", "Tập thể"],
    ["Nông cạn", "Sâu sắc"]
  ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = clues;
} 